apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: dev-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: dev-platform
rules:
- apiGroups: ["", "apps", "autoscaling"]
  resources: ["deployments", "services", "persistentvolumeclaims", "horizontalpodautoscalers", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: dev-platform
subjects:
- kind: ServiceAccount
  name: backend-sa
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: dev-platform
roleRef:
  kind: ClusterRole
  name: backend-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: backend
        image: p1yush123/spe-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-svc:27017"
        - name: ELASTICSEARCH_URI
          value: "http://host.minikube.internal:9200"
        - name: LOGSTASH_URL
          value: "http://host.minikube.internal:5044"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: dev-platform
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 5002
    targetPort: 5002
